#[tasks.format]
#install_crate = "rustfmt"
#command = "cargo"
#args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build_fw]
command = "cargo"
args = ["build", "--color=always", "--features=embedded", "--target=thumbv7em-none-eabihf"]

# unit tests for different OS targets
[tasks.unit_test]
linux_alias = "unit_test_linux"
windows_alias = "unit_test_windows"

[tasks.unit_test_windows]
command = "cargo"
args = ["test", "--color=always", "--features=std", "--target=x86_64-pc-windows-msvc"]
dependencies = ["clean"]

[tasks.unit_test_linux]
command = "cargo"
args = ["test", "--color=always", "--features=std", "--target=x86_64-unknown-linux-gnu"]
dependencies = ["clean"]